# Generated by Django 3.1.4 on 2020-12-13 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_auto_20201213_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
